package org.jboss.brms.common.util;

import java.util.HashMap;
import java.util.Map;

import org.mvel2.templates.CompiledTemplate;
import org.mvel2.templates.TemplateCompiler;
import org.mvel2.templates.TemplateRuntime;

public class MvelUtils {

	/**
	 * Returns the {@link String} generated by populating the
	 * given template with values from the given inputMap.
	 * @param template
	 * @param inputMap
	 * @return
	 */
	public static String generateResourceFromTemplate(String template, Map<String, Object> inputMap) {
		CompiledTemplate compiledTemplate = TemplateCompiler.compileTemplate(template);
		return (String) TemplateRuntime.execute(compiledTemplate, inputMap, new HashMap<String, Object>());
	}


}
